[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["cd srcs/backend && npm ci"]

[phases.build]
cmds = ["cd srcs/backend && npm run build"]

[start]
cmd = "cd srcs/backend && npm start"


